export function ImagesPokemon() {
  return [
    {
      image:
        "https://www.pokemon.com/static-assets/content-assets/cms2/img/pokedex/full/001.png",
    },
    {
      image:
        "https://www.pokemon.com/static-assets/content-assets/cms2/img/pokedex/full/002.png",
    },
    {
      image:
        "https://www.pokemon.com/static-assets/content-assets/cms2/img/pokedex/full/003.png",
    },
    {
      image:
        "https://www.pokemon.com/static-assets/content-assets/cms2/img/pokedex/full/004.png",
    },
    {
      image:
        "https://www.pokemon.com/static-assets/content-assets/cms2/img/pokedex/full/005.png",
    },
    {
      image:
        "https://www.pokemon.com/static-assets/content-assets/cms2/img/pokedex/full/006.png",
    },
    {
      image:
        "https://www.pokemon.com/static-assets/content-assets/cms2/img/pokedex/full/007.png",
    },
    {
      image:
        "https://www.pokemon.com/static-assets/content-assets/cms2/img/pokedex/full/008.png",
    },
    {
      image:
        "https://www.pokemon.com/static-assets/content-assets/cms2/img/pokedex/full/009.png",
    },
    {
      image:
        "https://www.pokemon.com/static-assets/content-assets/cms2/img/pokedex/full/010.png",
    },
    {
      image:
        "https://www.pokemon.com/static-assets/content-assets/cms2/img/pokedex/full/011.png",
    },
    {
      image:
        "https://www.pokemon.com/static-assets/content-assets/cms2/img/pokedex/full/012.png",
    },
    {
      image:
        "https://www.pokemon.com/static-assets/content-assets/cms2/img/pokedex/full/013.png",
    },
    {
      image:
        "https://www.pokemon.com/static-assets/content-assets/cms2/img/pokedex/full/014.png",
    },
    {
      image:
        "https://www.pokemon.com/static-assets/content-assets/cms2/img/pokedex/full/015.png",
    },
    {
      image:
        "https://www.pokemon.com/static-assets/content-assets/cms2/img/pokedex/full/016.png",
    },
    {
      image:
        "https://www.pokemon.com/static-assets/content-assets/cms2/img/pokedex/full/017.png",
    },
    {
      image:
        "https://www.pokemon.com/static-assets/content-assets/cms2/img/pokedex/full/018.png",
    },
    {
      image:
        "https://www.pokemon.com/static-assets/content-assets/cms2/img/pokedex/full/019.png",
    },
    {
      image:
        "https://www.pokemon.com/static-assets/content-assets/cms2/img/pokedex/full/020.png",
    },
  ];
}
